In [43]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib as plt

In [44]:
df = pd.read_csv("dirty_cafe_sales.csv")
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [46]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [47]:
df.describe(include = 'all')

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [50]:
numeric = ['Quantity', 'Price Per Unit', 'Total Spent',]
for col in numeric:
    df[col] = pd.to_numeric(df[col], errors = 'coerce')
    df[col] = df[col].fillna(0)
    df[col] = df[col].astype(int)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          10000 non-null  int64
 3   Price Per Unit    10000 non-null  int64
 4   Total Spent       10000 non-null  int64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: int64(3), object(5)
memory usage: 625.1+ KB

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3,12,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1,0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,2023-06-11

In [51]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors= 'coerce')
df.head()

df = df.sort_values('Transaction Date').reset_index(drop=True)
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_4801947,Juice,1,3,3,Digital Wallet,Takeaway,2023-01-01
1,TXN_9161256,Smoothie,2,4,8,Digital Wallet,In-store,2023-01-01
2,TXN_6093955,Tea,5,1,0,UNKNOWN,Takeaway,2023-01-01
3,TXN_8842223,Sandwich,5,0,20,Digital Wallet,In-store,2023-01-01
4,TXN_7367474,Juice,5,3,15,Digital Wallet,Takeaway,2023-01-01

In [52]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [53]:
modus = df['Location'].mode()
df['Location'] = df["Location"].replace("UNKNOWN", np.nan)
df['Location'] = df['Location'].fillna(modus)
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2579
Location            3603
Transaction Date     460
dtype: int64

In [54]:
objek = ['Payment Method', 'Location', 'Item']
for col in objek:
    modus = df[col].mode()[0]
    df[col] = df[col].fillna(modus)
df.isnull().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [56]:
df['Transaction Date'] = df['Transaction Date'].ffill()
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [58]:
df.to_csv('cafe_sales_clean.csv', index=False)